Fix Docker build
Kiro47/MTU-Transfer-Course-Gatherer pull request #69
Opened 2020-08-27 17:24 UTC by codetheweb

2020-08-27 17:26 UTC, codetheweb commented
8f3df02 failed to build with the new Workflow as expected 👍

2020-08-27 17:33 UTC, codetheweb commented
If @Blu3spirits can confirm that theme saving isn't broken, this should be good to go.

2020-08-28 00:37 UTC, Blu3spirits requested changes
> If @Blu3spirits can confirm that theme saving isn't broken, this should be good to go.

Wrote up my response here:
https://github.com/Kiro47/MTU-Transfer-Course-Gatherer/issues/67#issuecomment-682259743

TL;DR theme _saving_ wasn't broken, just theme loading due to a missing case of if storedTheme === dark

2020-08-28 00:37 UTC, Blu3spirits commented on Dockerfile
> -RUN npm ci --only=production
I think we should just define typescript as a prod dep.

2020-08-28 15:19 UTC, Blu3spirits approved these changes

2020-08-28 15:47 UTC, merged